apiVersion: apps/v1
kind: Deployment
metadata:
        name: abc2
        namespace: dev
        labels:
                color: blue 
spec:
        replicas: 3
        selector:
                matchLabels:
                        color: blue 
        template:
                metadata:
                        labels:
                                color: blue
        volumes:
                - name: vol1
                  hostPath:
                          path: /data  
                spec:
                        containers:
                                - name: abc-container
                                  image: gcr.io/amresh007/version1
                                  ports:
                                          - containerPort: 80
                                  volumeMounts:
                                          - name: vol1
                                            mountPath: /data

        

