apiVersion: v1
kind: Pod       
metadata:
        name: my-pod
        namespace: dev
spec:
        containers:
        - name: my-pod-containers
          image: gcr.io/amresh007/version1
        volumes:
                - name: task-pv-volume
                  hostPath:
                          path: /mnt
          resources:
                  limits:
                          memory: "200Mi"
                  requests:
                          memory: "100Mi"





     
