apiVersion: v1
kind: Service
metadata:
        name: service2
        namespace: dev
spec:
        selector:
                color: blue
        ports:
                - protocol: TCP
                  port: 80
        type: NodePort

