apiVersion: v1
kind: Service
metadata:
        name: my-first-service
        namespace: dev
spec:
        selector:
                color: orange
        ports:
                - protocol: TCP
                  port: 80
        type: ClusterIP

